import os

folders = {1: 'Counter',
           2: 'Stack',
           3: 'Type Utilities',
           4: 'Insertion Sort',
           5: 'Type Utilities II',
           6: 'Binary Search',
           7: 'Debounce',
           8: 'Depth-First Search',
           9: 'Heap Sort',
           10: 'Queue',
           11: 'Flatten',
           12: 'Merge Sort',
           13: 'Promise.all',
           14: 'Quick Sort',
           15: 'Todo List',
           16: 'Topological Sort',
           17: 'Deep Clone',
           18: 'Array.prototype.square',
           19: 'Get',
           20: 'Once',
           21: 'Selection Sort',
           22: 'Unique Array',
           23: 'Accordion',
           24: 'Array.prototype.filter',
           25: 'Array.prototype.map',
           26: 'Array.prototype.reduce',
           27: 'Function.prototype.bind',
           28: 'Generate Table',
           29: 'jQuery.css',
           30: 'Progress Bar',
           31: 'Progress Bars',
           32: 'Promise.race',
           33: 'Sum',
           34: 'Temperature Converter',
           35: 'Curry',
           36: 'Limit',
           37: 'Tabs',
           38: 'Throttle',
           39: 'Accordion II',
           40: 'Accordion III',
           41: 'Analog Clock',
           42: 'Camel Case Keys',
           43: 'Classnames',
           44: 'Curry II',
           45: 'Debounce II',
           46: 'Event Emitter',
           47: 'Event Emitter II',
           48: 'getElementsByTagName',
           49: 'Grid Lights',
           50: 'HTML Serializer',
           51: 'Identical DOM Trees',
           52: 'jQuery Class Manipulation',
           53: 'Like Button',
           54: 'List Format',
           55: 'Progress Bars II',
           56: 'Promise.allSettled',
           57: 'Promise.any',
           58: 'Squash Object',
           59: 'Star Rating',
           60: 'Tabs II',
           61: 'Tabs III',
           62: 'Text Search',
           63: 'Traffic Light',
           64: 'Deep Equal',
           65: 'Digital Clock',
           66: 'getElementsByClassName',
           67: 'Progress Bars III',
           68: 'Text Search II',
           69: 'Signup Form',
           70: 'Stopwatch',
           71: 'Curry III',
           72: 'Progress Bars IV',
           73: 'Data Selection',
           74: 'Table of Contents',
           75: 'Deep Clone II',
           76: 'JSON.stringify'}

for number, folder in folders.items():
    os.makedirs(str(number) + '. ' + folder)
    with open(os.path.join(str(number) + '. ' + folder, 'README.md'), 'w') as f:
        f.write('# ' + str(number) + '. ' + folder + '\n')
